import Cronologia
open Cronologia

def novela : Novela :=
  { localizaciones :=
      [ { id := 1, padre := some 10 },
        { id := 2, padre := some 10 },
        { id := 3, padre := some 10 },
        { id := 4, padre := none },
        { id := 5, padre := some 8 },
        { id := 6, padre := some 8 },
        { id := 7, padre := some 10 },
        { id := 8, padre := some 4 },
        { id := 9, padre := some 10 },
        { id := 10, padre := some 4 } ],
    personajes :=
      [ { id := 1, nacimiento := none },
        { id := 2, nacimiento := some (734815, 734815) },
        { id := 3, nacimiento := none } ],
    eventos :=
      [ { id := 1, momento := .recuerdo 738733 738763, lugar := 7, presentes := [],
          excluye := none },
        { id := 2, momento := .recuerdo 739099 739129, lugar := 5, presentes := [],
          excluye := none },
        { id := 3, momento := .recuerdo 739099 739129, lugar := 6, presentes := [],
          excluye := none },
        { id := 4, momento := .historia 1 .manana, lugar := 2, presentes := [2, 3],
          excluye := none },
        { id := 5, momento := .historia 1 .manana, lugar := 2, presentes := [2, 3],
          excluye := none },
        { id := 6, momento := .recuerdo 738733 738763, lugar := 7, presentes := [2, 3],
          excluye := none },
        { id := 7, momento := .recuerdo 738733 738763, lugar := 2, presentes := [2],
          excluye := none },
        { id := 8, momento := .historia 1 .tarde, lugar := 2, presentes := [2, 3],
          excluye := none },
        { id := 9, momento := .historia 2 .manana, lugar := 1, presentes := [2, 3],
          excluye := none },
        { id := 10, momento := .historia 2 .manana, lugar := 1, presentes := [2, 3],
          excluye := none },
        { id := 11, momento := .historia 2 .manana, lugar := 1, presentes := [2, 3],
          excluye := none },
        { id := 12, momento := .historia 2 .manana, lugar := 1, presentes := [1, 2, 3],
          excluye := none },
        { id := 13, momento := .historia 2 .manana, lugar := 1, presentes := [2, 3],
          excluye := none },
        { id := 14, momento := .historia 2 .tarde, lugar := 8, presentes := [1, 2, 3],
          excluye := none },
        { id := 15, momento := .recuerdo 739099 739129, lugar := 6, presentes := [2],
          excluye := none },
        { id := 16, momento := .historia 2 .tarde, lugar := 8, presentes := [1, 2, 3],
          excluye := none },
        { id := 17, momento := .historia 3 .manana, lugar := 2, presentes := [1, 2, 3],
          excluye := none },
        { id := 18, momento := .historia 3 .manana, lugar := 2, presentes := [1, 2, 3],
          excluye := none },
        { id := 19, momento := .historia 3 .manana, lugar := 2, presentes := [1, 2, 3],
          excluye := none },
        { id := 20, momento := .historia 3 .tarde, lugar := 3, presentes := [1, 2, 3],
          excluye := none },
        { id := 21, momento := .historia 3 .tarde, lugar := 3, presentes := [1, 2, 3],
          excluye := none },
        { id := 22, momento := .historia 3 .tarde, lugar := 3, presentes := [1, 2, 3],
          excluye := none },
        { id := 23, momento := .historia 4 .noche, lugar := 10, presentes := [1, 2, 3],
          excluye := none },
        { id := 24, momento := .historia 4 .noche, lugar := 10, presentes := [1, 2, 3],
          excluye := none },
        { id := 25, momento := .historia 4 .noche, lugar := 10, presentes := [1, 2, 3],
          excluye := none },
        { id := 26, momento := .historia 4 .noche, lugar := 10, presentes := [1, 2, 3],
          excluye := none },
        { id := 27, momento := .historia 4 .noche, lugar := 9, presentes := [2, 3],
          excluye := none },
        { id := 28, momento := .historia 4 .noche, lugar := 9, presentes := [2, 3],
          excluye := none },
        { id := 29, momento := .historia 4 .noche, lugar := 9, presentes := [2, 3],
          excluye := none },
        { id := 30, momento := .historia 4 .noche, lugar := 9, presentes := [2, 3],
          excluye := none },
        { id := 31, momento := .historia 4 .noche, lugar := 9, presentes := [2, 3],
          excluye := none },
        { id := 32, momento := .historia 4 .manana, lugar := 9, presentes := [1, 2, 3],
          excluye := none },
        { id := 33, momento := .historia 4 .manana, lugar := 9, presentes := [1, 2, 3],
          excluye := none },
        { id := 34, momento := .historia 4 .manana, lugar := 9, presentes := [1, 2, 3],
          excluye := none },
        { id := 35, momento := .historia 5 .manana, lugar := 7, presentes := [1, 2, 3],
          excluye := none },
        { id := 36, momento := .historia 5 .manana, lugar := 7, presentes := [1, 2, 3],
          excluye := none },
        { id := 37, momento := .historia 5 .manana, lugar := 7, presentes := [1, 2, 3],
          excluye := none },
        { id := 38, momento := .historia 6 .tarde, lugar := 2, presentes := [1, 2, 3],
          excluye := none },
        { id := 39, momento := .historia 6 .tarde, lugar := 2, presentes := [1, 2, 3],
          excluye := none },
        { id := 40, momento := .historia 6 .tarde, lugar := 2, presentes := [1, 2, 3],
          excluye := none },
        { id := 41, momento := .historia 6 .tarde, lugar := 2, presentes := [1, 2, 3],
          excluye := none },
        { id := 42, momento := .historia 6 .noche, lugar := 2, presentes := [2, 3],
          excluye := none } ] }

theorem lugar_unico : lugarUnico novela = true := by decide +kernel
theorem sin_reaparicion : sinReaparicion novela = true := by decide +kernel
theorem nacido_antes : nacidoAntes novela = true := by decide +kernel

#eval violaciones novela
